version: 2

models:
  - name: risk_metrics
    description: "Raw hourly VaR (Value-at-Risk) and LaR (Liquidations-at-Risk) metrics computed from a 1-hour rolling window."
    columns:
      - name: snapshot_time
        description: "Timestamp (UTC) when metrics were published."
        tests:
          - not_null
          - unique
      - name: var
        description: "1st percentile of the past 60 minute-resolution P&L deltas (99% VaR)."
        tests:
          - not_null
      - name: lar
        description: "Total outstanding debt in reference currency for any user whose health factor < 1."
        tests:
          - not_null

  - name: risk_deltas
    description: "Minute‐resolution P&L snapshots and their delta from the previous minute."
    columns:
      - name: snapshot_time
        description: "Timestamp (UTC) when the snapshot was taken."
        tests:
          - not_null
          - unique
      - name: value
        description: "Total net value of all users (collateral − debt)."
        tests:
          - not_null
      - name: delta
        description: "Change in net value since the previous snapshot."
        tests:
          - not_null

  - name: hourly_metrics
    description: "Hourly aggregates of VaR & LaR over each hour."
    columns:
      - name: hour
        description: "The UTC hour for which aggregates are computed."
        tests:
          - not_null
          - unique
      - name: avg_var
        description: "Average VaR during the hour."
        tests:
          - not_null
      - name: min_var
        description: "Minimum VaR during the hour."
        tests:
          - not_null
      - name: max_var
        description: "Maximum VaR during the hour."
        tests:
          - not_null
      - name: avg_lar
        description: "Average LaR during the hour."
        tests:
          - not_null

  - name: hourly_deltas
    description: "Hourly aggregates of minute‐resolution deltas."
    columns:
      - name: hour
        description: "The UTC hour for which aggregates are computed."
        tests:
          - not_null
          - unique
      - name: avg_delta
        description: "Average minute‐to‐minute delta during the hour."
        tests:
          - not_null
      - name: min_delta
        description: "Minimum delta during the hour."
        tests:
          - not_null
      - name: max_delta
        description: "Maximum delta during the hour."
        tests:
          - not_null
