services:
  redpanda:
    image: redpandadata/redpanda:v23.3.10
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --advertise-kafka-addr=redpanda:9092
    ports:
      - "9092:9092"
      - "29092:29092"
